### ISSUE TITLE
a error on ./mirror start

### ISSUE THREAD

**Issue by RioxArevia** [poorfella/mirrorcsgo#1]
debian 10 & ubuntu 20
root@murk~# ./mirror start
./mirror: line 1: Lz8!X1▒1▒▒c▒L@▒▒▒▒I▒▒=Lذ▒.+ãT▒▒▒ȓAU: No such file or directory
./mirror: line 2: syntax error near unexpected token `$'X\231!؎\213\2748mA\366\343\353W\020\373\341''
./mirror: line 2: `Nގ(X▒!؎▒▒8mA▒▒▒W▒▒)5▒+}▒~▒▒E▒[U▒sA1▒ 1▒▒W▒z͋e▒}▒/▒I▒▒▒3▒▒▒3.w▒:▒~4
▒U▒ݾ▒   z7(▒▒n  ▒j▒▒Te'

**Comment by poorfella** [comment]
I was told to spill the beans and due to my hesitations I uploaded below par release
So I've received several error reports from Russian mates mainly using the latest version of Ubuntu
I am close to fix this issue and will update it within minutes
