### ISSUE TITLE
a error

### ISSUE THREAD

**Issue by RioxArevia** [poorfella/mirrorcsgo#2]
hi:
root@murky-cub:~/mirrorcsgo-main# ./mirror start
-bash: ./mirror: cannot execute binary file: Exec format error

ubuntu 20

**Comment by poorfella** [comment]
Yes, there was an issues with executable file
I needed to recompile it for different architectures, my bad
I was ready to release more of the source code, so everyone could compile the code themselves, however, I have to close the project.
